### ISSUE TITLE
Sensor for door state

### ISSUE THREAD

**Issue by Partizan7676** [AprilBrother/ESPea-Examples#2]
Is it possible add two sensors? One will control door state, other can be used as doorbell button ?

**Comment by volca** [comment]
Do you talk about the sketch [http-lock](https://github.com/AprilBrother/ESPea-Examples/tree/master/examples/04.Network/http-lock)?

**Comment by Partizan7676** [comment]
Yes, but little change my opinion. Only close/open sensor will useful.

**Comment by Partizan7676** [comment]
Would you advise me where changing username and password? In esp8266webserver.h Am I  right?

**Comment by volca** [comment]
> Would you advise me where changing username and password? In esp8266webserver.h Am I right?

Do you mean the username and password in config.json? You should not modify esp8266webserver.h.   Change the http-lock.ino

```
    String username = server.arg("username");
    String password = server.arg("password");

    if (username == "test" && password == "test") {
        // do more things
    }

```

**Comment by Partizan7676** [comment]
Thanks! Which one must be changed? Replace test with my own?

**Comment by volca** [comment]
> Thanks! Which one must be changed? Replace test with my own?

yes

**Comment by mohamedkeven** [comment]
can you help me ?!!

**Comment by mohamedkeven** [comment]
this work witth wemo d1 mini ??

**Comment by volca** [comment]
yes. They should be compatible

**Comment by volca** [comment]
@mohamedkeven please open a new issue if for your question closed the issue
